scanner: scanner.c
	gcc -o scanner scanner.c

P-Machine: P-Machine.c
	gcc -o P-Machine P-Machine.c

ParserCodeGenerator: ParserCodeGenerator.c ParserCodeGenerator.h
	gcc -o ParserCodeGenerator ParserCodeGenerator.c

compiler: CompileDriver.c
	gcc -o compiler CompileDriver.c
